name: Build Tauri App (.deb) and Upload to Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libssl-dev build-essential curl wget squashfs-tools

      - name: Install Rust dependencies
        run: |
          cargo install tauri-cli

      - name: Build .deb
        working-directory: src-tauri
        run: |
          cargo tauri build

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/deb/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
